/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AdminRole = { 'customerSupport' : null } |
  { 'productManager' : null } |
  { 'superAdmin' : null } |
  { 'orderManager' : null };
export interface AdminUser {
  'id' : Principal,
  'name' : string,
  'role' : AdminRole,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type ExternalBlob = Uint8Array;
export interface FeaturedCollection {
  'title' : string,
  'countdown' : string,
  'items' : Array<Product>,
}
export interface Lookbook { 'id' : string, 'products' : Array<Product> }
export interface Order {
  'id' : string,
  'status' : OrderStatus,
  'customer' : Principal,
  'createdAt' : Time,
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface PaymentMethodsConfig {
  'stripeApiKey' : [] | [string],
  'acceptedCardTypes' : Array<string>,
  'enableStripe' : boolean,
}
export interface Product {
  'id' : string,
  'name' : string,
  'color' : string,
  'description' : string,
  'seasonal' : boolean,
  'designer' : string,
  'stock' : bigint,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface Review {
  'userId' : Principal,
  'createdAt' : Time,
  'productId' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface RewardPoints {
  'studentDiscountEligible' : boolean,
  'userId' : Principal,
  'createdAt' : Time,
  'birthdayEligible' : boolean,
  'points' : bigint,
}
export interface ShippingRates {
  'regionShippingCosts' : Array<[string, bigint]>,
  'flatRate' : bigint,
  'freeShippingThreshold' : bigint,
}
export interface ShoppingCart { 'items' : Array<CartItem> }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreInfo {
  'name' : string,
  'address' : string,
  'contactEmail' : string,
  'phoneNumber' : string,
}
export interface StoreSettings {
  'adminRoles' : Array<AdminUser>,
  'logo' : [] | [ExternalBlob],
  'shippingRates' : ShippingRates,
  'themeColors' : ThemeColors,
  'taxSettings' : TaxSettings,
  'storeInfo' : StoreInfo,
  'paymentMethods' : PaymentMethodsConfig,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TaxSettings {
  'salesTaxPercentage' : number,
  'taxExemptRegions' : Array<string>,
}
export interface ThemeColors {
  'primary1' : string,
  'primary2' : string,
  'primary3' : string,
  'secondary1' : string,
  'secondary2' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Wishlist { 'productIds' : Array<string> }
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addReview' : ActorMethod<[Review], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'addToWishlist' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFeaturedCollection' : ActorMethod<[FeaturedCollection], undefined>,
  'createLookbook' : ActorMethod<[Lookbook], undefined>,
  'createOrder' : ActorMethod<[Order], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], ShoppingCart>,
  'getFeaturedCollections' : ActorMethod<[], Array<FeaturedCollection>>,
  'getLookbooks' : ActorMethod<[], Array<Lookbook>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getProductReviews' : ActorMethod<[string], Array<Review>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getRewardPoints' : ActorMethod<[], RewardPoints>,
  'getStoreSettings' : ActorMethod<[], [] | [StoreSettings]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Wishlist>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'removeFromWishlist' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAdminRoles' : ActorMethod<[Array<AdminUser>], undefined>,
  'updateLogo' : ActorMethod<[ExternalBlob], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'updatePaymentMethods' : ActorMethod<[PaymentMethodsConfig], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateRewardPoints' : ActorMethod<[RewardPoints], undefined>,
  'updateShippingRates' : ActorMethod<[ShippingRates], undefined>,
  'updateStoreInfo' : ActorMethod<[StoreInfo], undefined>,
  'updateStoreSettings' : ActorMethod<[StoreSettings], undefined>,
  'updateTaxSettings' : ActorMethod<[TaxSettings], undefined>,
  'updateThemeColors' : ActorMethod<[ThemeColors], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];