/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'description' : IDL.Text,
  'seasonal' : IDL.Bool,
  'designer' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Time = IDL.Int;
export const Review = IDL.Record({
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'productId' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const FeaturedCollection = IDL.Record({
  'title' : IDL.Text,
  'countdown' : IDL.Text,
  'items' : IDL.Vec(Product),
});
export const Lookbook = IDL.Record({
  'id' : IDL.Text,
  'products' : IDL.Vec(Product),
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : OrderStatus,
  'customer' : IDL.Principal,
  'createdAt' : Time,
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(CartItem),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
});
export const ShoppingCart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const RewardPoints = IDL.Record({
  'studentDiscountEligible' : IDL.Bool,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'birthdayEligible' : IDL.Bool,
  'points' : IDL.Nat,
});
export const AdminRole = IDL.Variant({
  'customerSupport' : IDL.Null,
  'productManager' : IDL.Null,
  'superAdmin' : IDL.Null,
  'orderManager' : IDL.Null,
});
export const AdminUser = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'role' : AdminRole,
});
export const ShippingRates = IDL.Record({
  'regionShippingCosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'flatRate' : IDL.Nat,
  'freeShippingThreshold' : IDL.Nat,
});
export const ThemeColors = IDL.Record({
  'primary1' : IDL.Text,
  'primary2' : IDL.Text,
  'primary3' : IDL.Text,
  'secondary1' : IDL.Text,
  'secondary2' : IDL.Text,
});
export const TaxSettings = IDL.Record({
  'salesTaxPercentage' : IDL.Float64,
  'taxExemptRegions' : IDL.Vec(IDL.Text),
});
export const StoreInfo = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactEmail' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const PaymentMethodsConfig = IDL.Record({
  'stripeApiKey' : IDL.Opt(IDL.Text),
  'acceptedCardTypes' : IDL.Vec(IDL.Text),
  'enableStripe' : IDL.Bool,
});
export const StoreSettings = IDL.Record({
  'adminRoles' : IDL.Vec(AdminUser),
  'logo' : IDL.Opt(ExternalBlob),
  'shippingRates' : ShippingRates,
  'themeColors' : ThemeColors,
  'taxSettings' : TaxSettings,
  'storeInfo' : StoreInfo,
  'paymentMethods' : PaymentMethodsConfig,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const Wishlist = IDL.Record({ 'productIds' : IDL.Vec(IDL.Text) });
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addReview' : IDL.Func([Review], [], []),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addToWishlist' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createFeaturedCollection' : IDL.Func([FeaturedCollection], [], []),
  'createLookbook' : IDL.Func([Lookbook], [], []),
  'createOrder' : IDL.Func([Order], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [ShoppingCart], ['query']),
  'getFeaturedCollections' : IDL.Func(
      [],
      [IDL.Vec(FeaturedCollection)],
      ['query'],
    ),
  'getLookbooks' : IDL.Func([], [IDL.Vec(Lookbook)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRewardPoints' : IDL.Func([], [RewardPoints], ['query']),
  'getStoreSettings' : IDL.Func([], [IDL.Opt(StoreSettings)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [Wishlist], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAdminRoles' : IDL.Func([IDL.Vec(AdminUser)], [], []),
  'updateLogo' : IDL.Func([ExternalBlob], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  'updatePaymentMethods' : IDL.Func([PaymentMethodsConfig], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateRewardPoints' : IDL.Func([RewardPoints], [], []),
  'updateShippingRates' : IDL.Func([ShippingRates], [], []),
  'updateStoreInfo' : IDL.Func([StoreInfo], [], []),
  'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
  'updateTaxSettings' : IDL.Func([TaxSettings], [], []),
  'updateThemeColors' : IDL.Func([ThemeColors], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'description' : IDL.Text,
    'seasonal' : IDL.Bool,
    'designer' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Time = IDL.Int;
  const Review = IDL.Record({
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'productId' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const FeaturedCollection = IDL.Record({
    'title' : IDL.Text,
    'countdown' : IDL.Text,
    'items' : IDL.Vec(Product),
  });
  const Lookbook = IDL.Record({
    'id' : IDL.Text,
    'products' : IDL.Vec(Product),
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : OrderStatus,
    'customer' : IDL.Principal,
    'createdAt' : Time,
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(CartItem),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
  });
  const ShoppingCart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const RewardPoints = IDL.Record({
    'studentDiscountEligible' : IDL.Bool,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'birthdayEligible' : IDL.Bool,
    'points' : IDL.Nat,
  });
  const AdminRole = IDL.Variant({
    'customerSupport' : IDL.Null,
    'productManager' : IDL.Null,
    'superAdmin' : IDL.Null,
    'orderManager' : IDL.Null,
  });
  const AdminUser = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'role' : AdminRole,
  });
  const ShippingRates = IDL.Record({
    'regionShippingCosts' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'flatRate' : IDL.Nat,
    'freeShippingThreshold' : IDL.Nat,
  });
  const ThemeColors = IDL.Record({
    'primary1' : IDL.Text,
    'primary2' : IDL.Text,
    'primary3' : IDL.Text,
    'secondary1' : IDL.Text,
    'secondary2' : IDL.Text,
  });
  const TaxSettings = IDL.Record({
    'salesTaxPercentage' : IDL.Float64,
    'taxExemptRegions' : IDL.Vec(IDL.Text),
  });
  const StoreInfo = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactEmail' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const PaymentMethodsConfig = IDL.Record({
    'stripeApiKey' : IDL.Opt(IDL.Text),
    'acceptedCardTypes' : IDL.Vec(IDL.Text),
    'enableStripe' : IDL.Bool,
  });
  const StoreSettings = IDL.Record({
    'adminRoles' : IDL.Vec(AdminUser),
    'logo' : IDL.Opt(ExternalBlob),
    'shippingRates' : ShippingRates,
    'themeColors' : ThemeColors,
    'taxSettings' : TaxSettings,
    'storeInfo' : StoreInfo,
    'paymentMethods' : PaymentMethodsConfig,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const Wishlist = IDL.Record({ 'productIds' : IDL.Vec(IDL.Text) });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addReview' : IDL.Func([Review], [], []),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addToWishlist' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createFeaturedCollection' : IDL.Func([FeaturedCollection], [], []),
    'createLookbook' : IDL.Func([Lookbook], [], []),
    'createOrder' : IDL.Func([Order], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [ShoppingCart], ['query']),
    'getFeaturedCollections' : IDL.Func(
        [],
        [IDL.Vec(FeaturedCollection)],
        ['query'],
      ),
    'getLookbooks' : IDL.Func([], [IDL.Vec(Lookbook)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProductReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRewardPoints' : IDL.Func([], [RewardPoints], ['query']),
    'getStoreSettings' : IDL.Func([], [IDL.Opt(StoreSettings)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [Wishlist], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAdminRoles' : IDL.Func([IDL.Vec(AdminUser)], [], []),
    'updateLogo' : IDL.Func([ExternalBlob], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
    'updatePaymentMethods' : IDL.Func([PaymentMethodsConfig], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateRewardPoints' : IDL.Func([RewardPoints], [], []),
    'updateShippingRates' : IDL.Func([ShippingRates], [], []),
    'updateStoreInfo' : IDL.Func([StoreInfo], [], []),
    'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
    'updateTaxSettings' : IDL.Func([TaxSettings], [], []),
    'updateThemeColors' : IDL.Func([ThemeColors], [], []),
  });
};

export const init = ({ IDL }) => { return []; };